"""Modbus Packet Classes.

Packet classes for Modbus TCP and Modbus RTU, split by data-flow stage:
base declares the abstractions, pdu carries the function-code classes,
framing carries the MBAP header and the two ADU families. Every name is
re-exported here, so the import path is unchanged.

A custom PDU subclasses ModbusPdu and registers with ModbusPduParser,
giving its format string, function code and PDU identifier. See
docs/PLAYBOOK.md for the identifier ranges.
"""

from pyomb.packets.base import (
    ModbusPacketAbc,
    ModbusPduParserAbc,
    ModbusViolation,
)
from pyomb.packets.framing import (
    CRC_FMT,
    CRC_SIZE,
    ModbusHeader,
    ModbusRtuPacket,
    ModbusRtuRequest,
    ModbusRtuResponse,
    ModbusRtuSniffer,
    ModbusRtuSplitter,
    ModbusTcpPacket,
    ModbusTcpRequest,
    ModbusTcpResponse,
    RtuSide,
    RtuSniffedFrame,
    RtuSyncState,
    calc_crc16,
    validate_crc,
    validate_mbap_length,
)
from pyomb.packets.pdu import (
    ModbusError,
    ModbusPdu,
    ModbusPduParser,
    ModbusRequestFC1,
    ModbusRequestFC2,
    ModbusRequestFC3,
    ModbusRequestFC4,
    ModbusRequestFC5,
    ModbusRequestFC6,
    ModbusRequestFC7,
    ModbusRequestFC8,
    ModbusRequestFC15,
    ModbusRequestFC16,
    ModbusRequestFC22,
    ModbusRequestFC23,
    ModbusRequestFC43,
    ModbusResponseFC1,
    ModbusResponseFC2,
    ModbusResponseFC3,
    ModbusResponseFC4,
    ModbusResponseFC5,
    ModbusResponseFC6,
    ModbusResponseFC7,
    ModbusResponseFC8,
    ModbusResponseFC15,
    ModbusResponseFC16,
    ModbusResponseFC22,
    ModbusResponseFC23,
    ModbusResponseFC43,
)

__all__ = [
    "CRC_FMT",
    "CRC_SIZE",
    "ModbusError",
    "ModbusHeader",
    "ModbusPacketAbc",
    "ModbusPdu",
    "ModbusPduParser",
    "ModbusPduParserAbc",
    "ModbusRequestFC1",
    "ModbusRequestFC2",
    "ModbusRequestFC3",
    "ModbusRequestFC4",
    "ModbusRequestFC5",
    "ModbusRequestFC6",
    "ModbusRequestFC7",
    "ModbusRequestFC8",
    "ModbusRequestFC15",
    "ModbusRequestFC16",
    "ModbusRequestFC22",
    "ModbusRequestFC23",
    "ModbusRequestFC43",
    "ModbusResponseFC1",
    "ModbusResponseFC2",
    "ModbusResponseFC3",
    "ModbusResponseFC4",
    "ModbusResponseFC5",
    "ModbusResponseFC6",
    "ModbusResponseFC7",
    "ModbusResponseFC8",
    "ModbusResponseFC15",
    "ModbusResponseFC16",
    "ModbusResponseFC22",
    "ModbusResponseFC23",
    "ModbusResponseFC43",
    "ModbusRtuPacket",
    "ModbusRtuRequest",
    "ModbusRtuResponse",
    "ModbusRtuSniffer",
    "ModbusRtuSplitter",
    "ModbusTcpPacket",
    "ModbusTcpRequest",
    "ModbusTcpResponse",
    "ModbusViolation",
    "RtuSide",
    "RtuSniffedFrame",
    "RtuSyncState",
    "calc_crc16",
    "validate_crc",
    "validate_mbap_length",
]
